"""LeetCode 389. Find the Difference (Easy)

You are given two strings s and t. String t is generated by random shuffling
string s and then adding one more letter at a random position. Return the
letter that was added to t.
"""

from collections import Counter


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        counts = Counter(s)
        for ch in t:
            if counts[ch] == 0:
                return ch
            counts[ch] -= 1
        return ""  # unreachable given problem constraints
